import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{``}</style>
      <Head>
        <title>Manish&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, next blog, manish" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>Manish&apos;s Blog</span>
        </h1>
        <div className={styles.imageWrap}>
          <Image
            src="/manishblogheroimg.avif"
            width={414}
            height={274}
            alt="hero image"
            className={styles.myImg}
          ></Image>
        </div>

        <p className={styles.description}>A blog for coders by a coder.</p>
      </main>
    </div>
  );
}
